### PR TITLE
[Error handling] Fix concurrency issue when APIs are too slow

### LINKED ISSUE #808: Issue with never ending loader
**Description**
When one API is super slow is possible than the quote never loads.

**How to Reproduce**
Increase the `REFETCH_CHECK_INTERVAL` in https://github.com/gnosis/cowswap/blob/2712a4dbdca4c90e282c4e2a418b89d07372c49e/src/custom/state/price/updater.ts#L18-L18

**Additional context**
I did my tests using 1.5seconds of timeout, but when using the 10s and there’s a new price update coming (because we check periodically), then the app cancel the previous one, and starts a new fresher one

Problem, is that it never finish getting a quote, because it repeats this behaviour forever.

This issue happens if the refresh rate is higher than the request delay. It was actually happening also before adding the timeout. I think we need to not invalidate the previous request if there’s one going on with the same params

### PR DESCRIPTION
**Pull request by anxolin**
Closes #808 

Fix issue with refreshing prices while theres an ongoing quote query.

## Details

Prevents the issue that, if the querying of the quote happens at a faster pace than the API replying with the quote, we get to the situation where we always invalidate the previous queries and never let then finish!

The main solution to the problem is, now the `lastCheck` happens already when we ask for the quote, both for `getNewQuoteStart` and `refreshQuoteStart`

Since now the state is updated on the beginning of this asyncronous operation. If before is finished we try to update the prices (because for example, the price API is too slow and another scheduled check is triggered), then we will let the previous query to finish.

## Test
Before this PR, you can see that if you reduce `REFETCH_CHECK_INTERVAL` so is faster than the API, you never manage to fetch a price.

I also added a big delay to paraswap. For example adding to https://github.com/gnosis/cowswap/blob/cb65de7f48aa4d76c8c348f43c41956db4a09e5b/src/custom/utils/paraswap.ts#L57-L60 these lines:
```ts
if (params.amount) {
    // throw new Error('Boooom!')
    return new Promise(r => setTimeout(r, 10000000000))
  }
```

### CODE REVIEW

File: src/custom/state/price/updater.ts [hunk 1]
```diff
@@ -15,29 +15,14 @@ const DEBOUNCE_TIME = 350
...
-function priceIsOld(quoteInfo?: QuoteInformationObject): boolean {
-  const lastPriceCheck = quoteInfo?.lastCheck
-  if (!lastPriceCheck) {
-    return true
-  }
-  const isPriceOld = lastPriceCheck + PRICE_UPDATE_TIME < Date.now()
-  // console.log(`[state:price:updater] Price is old? `, isPriceOld)
-  return isPriceOld
-}
-
```
Comment (anxolin) [inline src/custom/state/price/updater.ts:40]: This was not needed. `wasQuoteCheckedRecently` should be enough

File: src/custom/state/price/updater.ts [hunk 2]
```diff
@@ -73,10 +58,14 @@ function quoteUsingSameParameters(currentParams: FeeQuoteParams, quoteInfo: Quot
...
  */
-function isRefetchQuoteRequired(currentParams: FeeQuoteParams, quoteInformation?: QuoteInformationObject): boolean {
+function isRefetchQuoteRequired(
+  isLoading: boolean,
+  currentParams: FeeQuoteParams,
+  quoteInformation?: QuoteInformationObject
+): boolean {
   // If there's no quote/fee information, we always re-fetch
   // we need to check that there is also no error otherwise this will loop
-  if (!quoteInformation || (!quoteInformation.fee && !quoteInformation.error)) {
```
Comment (anxolin) [inline src/custom/state/price/updater.ts:79]: we can simplify this. Since `getNewQuoteStart` already initializes the `quoteInformation` this won't be an issue anymore

File: src/custom/state/price/updater.ts [hunk 3]
```diff
@@ -87,11 +76,15 @@ function isRefetchQuoteRequired(currentParams: FeeQuoteParams, quoteInformation?
...
+  //  - There's not another price query going on right now
   //  - The quote will expire soon
-
   if (wasQuoteCheckedRecently(quoteInformation.lastCheck)) {
     // Don't Re-fetch if it was queried recently
     return false
+  } else if (isLoading) {
+    // Don't Re-fetch if there's another quote going on with the same params
+    // It's better to wait for the timeout or resolution. Also prevents an issue of refreshing too fast with slow APIs
+    return false
```
Comment (anxolin) [inline src/custom/state/price/updater.ts:87]: This line is the key of this PR

File: src/custom/state/price/updater.ts [hunk 4]
```diff
@@ -156,17 +153,20 @@ export default function FeesUpdater(): null {
...
+        // Decide if this is a new quote, or just a refresh
+        const thereIsPreviousPrice = !!quoteInfo?.price?.amount
+        const isJustPriceRefresh = quoteInfo
+          ? thereIsPreviousPrice && quoteUsingSameParameters(quoteParams, quoteInfo)
+          : false
 
         refetchQuote({
           quoteParams,
-          fetchFee: refetchAll,
+          fetchFee: true, // TODO: Review this, because probably now doesn't make any sense to not query the feee in some situations. Actually the endpoint will change to one that returns fee and quote together
```
Comment (anxolin) [inline src/custom/state/price/updater.ts:167]: We will need to revisit this part. 
Although for this PR should be fine. We always query the fee.

**Comment by biocom** [comment]
Think I found a critical error:

Screen Shot 2021-06-29 at 12 58 44

- Pair: USDC -> 1INCH
- Play with input amounts
- Play some more, but this time input 22222222222222 (ridiculous number)
- Still not breaking? Try swapping from SELL to BUY order a couple of times.

Error:
> tiny-invariant.esm.js:8 Uncaught Error: Invariant failed

**Comment by anxolin** [comment]
> Think I found a critical error:
I think this was fixed in https://github.com/gnosis/cowswap/pull/817

**Comment by anxolin** [comment]
Merging, pls @alfetopito @W3stside review this too.

File: src/custom/state/price/reducer.ts [hunk 5]
```diff
@@ -53,29 +53,60 @@ function initializeState(
   }
 }
 
+function getResetPrice(sellToken: string, buyToken: string, kind: string) {
+  return {
+    amount: null,
+    token: kind ? sellToken : buyToken
```
Comment (alfetopito) [inline src/custom/state/price/reducer.ts:59]: Shouldn't we make this kind a boolean, and call it `isSellToken`?
Because it's a string and the check is misleading.

Or make `kind: 'sell' | 'buy'` to be more explicit.

File: src/custom/state/price/updater.ts [hunk 6]
```diff
@@ -140,7 +133,10 @@ export default function FeesUpdater(): null {
 
   // Update if any parameter is changing
   useEffect(() => {
-    // Don't refetch if window is not visible, or some parameter is missing
+    // Don't refetch if:
+    //  - window is not visible
+    //  - browser is offline
```
Comment (alfetopito) [inline src/custom/state/price/updater.ts:138]: Where is the check for the offline flag?

File: src/custom/state/price/reducer.ts (hunk 5 above)
Comment (anxolin) [reply src/custom/state/price/reducer.ts:59]: Good catch!! I think this is important! 

I wiill actually do a hotfix for this.

Comment (anxolin) [reply src/custom/state/price/reducer.ts:59]: no hotfix needed, will do for 0.16: https://github.com/gnosis/cowswap/pull/845

File: src/custom/state/price/updater.ts (hunk 6 above)
Comment (anxolin) [reply src/custom/state/price/updater.ts:138]: Later! it was originally there but was moved (i left the comment)
