### PR TITLE
Fix change or disconnect wallet after claim confirm

### LINKED ISSUE #2251: 'Claimed!' screen is displayed when change account/disconnect a wallet
1. Do a successful claim
2. Change a wallet in the MM when Claimed! screen is displayed
3. Then disconnect all accounts

**AR**: 
2: the screen remains to be displayed
3: big moving 'Connect to a wallet' button is displayed

**ER**: user is redirected to the main claim page

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #2251

### CODE REVIEW

File: src/custom/pages/Claim/index.tsx [hunk 1]
```diff
@@ -174,7 +179,14 @@ export default function Claim() {
 
     // properly reset the user to the claims table and initial investment flow
     resetClaimUi()
-  }, [account, activeClaimAccount, resolvedAddress, isSearchUsed, setActiveClaimAccount, resetClaimUi])
+  }, [account, isSearchUsed, resetClaimUi, setActiveClaimAccount])
+
+  // handle account disconnect or account change after claim is confirmed
+  useEffect(() => {
+    if (!account || (account !== previousAccount && claimStatus === ClaimStatus.CONFIRMED)) {
```
Comment (W3stside) [inline src/custom/pages/Claim/index.tsx:186]: shouldn't the useEffect trigger on account change? why is previousAccount needed? I would think
```ts
useEffect(() => {
    if (!account || claimStatus === ClaimStatus.CONFIRMED) {
...
```
should work, it doesn't?

Comment (nenadV91) [reply src/custom/pages/Claim/index.tsx:186]: Since `claimStatus` is dependency this `(!account || claimStatus === ClaimStatus.CONFIRMED)` would activate instantly when the status becomes confirmed and you would not see claim success view at all. So instead this `account !== previousAccount && claimStatus === ClaimStatus.CONFIRMED` this will only activate when the account changes and the claim is confirmed.

**Review by W3stside — APPROVED** [review]

**Comment by nenadV91** [comment]
@alfetopito Just checked on release branch, looks like its still there when you disconnect the wallet after claim is confirmed you see this
Screenshot from 2022-01-28 01-14-28

**Comment by elena-zh** [comment]
Hey @nenadV91 , changes LGTM!
However, would it be better to navigate a user to this screen when change accounts
image
instead of this one?
image

The same is for the flow when open another page and then go back to the Claim page.

**Comment by nenadV91** [comment]
@elena-zh Should be all there now.

**Review by elena-zh — APPROVED** [review]
Great!
