### PR TITLE
Increase max slippage

### LINKED ISSUE #835: Paraswap price fails if price impact is too high
**Description**
The paraswap price fails if the price impact is too high

**How to Reproduce**
1. Go to Cowswap choose a random token pair
2. Do the same on Paraswap
3. Insert a value in Paraswap for which the price impact is too high or around 10%
4. Use this value on Cowswap
5.  The Price on Coswap is worse than Paraswap

**Expected behavior**
The same price should be displayed

**Screenshots**
Bildschirmfoto 2021-07-01 um 09 44 10
Bildschirmfoto 2021-07-01 um 10 05 58

### PR DESCRIPTION
**Pull request by anxolin**
image

As you can see, now we don't get the error 400 and we receive more tokens than in current production

Closes #835 #825

Related to https://github.com/gnosis/cowswap/pull/839, which will make the error to go away, so it's not a 400 anymore. 
Anyways, I think for resiliance is good to also do this error handling on top of https://github.com/gnosis/cowswap/pull/839.
Bot PRs independently solve the issue, but is good to have both

### CODE REVIEW

**Comment by W3stside** [comment]
👍

File: src/custom/utils/paraswap.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ export async function getPriceQuote(params: PriceQuoteParams): Promise<ParaSwapP
 
   // https://developers.paraswap.network/api/get-rate-for-a-token-pair
   const options: RateOptions | undefined = {
-    // maxImpact
+    maxImpact: 100
```
Comment (alfetopito) [inline src/custom/utils/paraswap.ts:89]: What does 100 mean? Add a comment for that maybe?
Couldn't find it in the API reference above
