### PR TITLE
Fix avilable claims issue on rinkeby

### LINKED ISSUE #2419: 'Available to claim' tokens are displayed in Rinkeby when a user is not eligible to claim
'Available to claim' tokens are displayed in Rinkeby when a user is not eligible to claim. See the image:

Expected: whether 0 tokens to claim should be displayed, or 'Claim' button should be enabled (if a user is eligible to claim)

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #2419

This scenario happens when there are no claimed or available claims but there is vCow balance, which means that user somehow has vCow balance but he didn't claim anything. So this probably shouldn't happen on Mainet or Gnosis Chain but happens on Rinkeby on accounts where you have vCow tokens from previous vCow contract deployments.

### CODE REVIEW

File: src/custom/pages/Claim/ClaimSummary.tsx [hunk 1]
```diff
@@ -53,7 +69,7 @@ export function ClaimSummaryView({ showClaimText, totalAvailableText, totalAvail
           </Trans>
         </ClaimSummaryTitle>
       )}
-      {totalAvailableAmount && (
+      {totalAvailableAmount && activeClaimAccount && (
```
Comment (alfetopito) [inline src/custom/pages/Claim/ClaimSummary.tsx:72]: I don't think you need this here, since the amount is only used as a flag.

You can control this in the parent component, as you already do.
I think it'll work the same without this extra parameter. Doesn't it?

**Review by elena-zh — APPROVED** [review]
LGTM

File: src/custom/pages/Claim/ClaimSummary.tsx (hunk 1 above)
Comment (nenadV91) [reply src/custom/pages/Claim/ClaimSummary.tsx:72]: I think we need this also because the `totalAvailableAmount` is now CurrencyAmount object by default and this happens otherwise
Screenshot from 2022-02-17 11-46-24

File: src/custom/pages/Claim/ClaimSummary.tsx [hunk 2]
```diff
@@ -19,16 +20,25 @@ export function ClaimSummary({ hasClaims, isClaimed, unclaimedAmount }: ClaimSum
...
+  const vCow = chainId ? V_COW[chainId] : undefined
+
+  const vCowBalance = useTokenBalance(activeClaimAccount || undefined, vCow)
 
   const hasClaimSummary = claimStatus === ClaimStatus.DEFAULT && !isInvestFlowActive
 
-  if (!hasClaimSummary) return null
+  if (!hasClaimSummary || !vCow) return null
+
+  let totalAvailableAmount: CurrencyAmount<Token> | undefined = CurrencyAmount.fromRawAmount(vCow, JSBI.BigInt(0))
```
Comment (nenadV91) [inline src/custom/pages/Claim/ClaimSummary.tsx:31]: This is now set to CurrencyAmount object by default because we want to show zero in this case and so that `formatSmartLocaleAware` and `formatMax` work

File: src/custom/pages/Claim/ClaimSummary.tsx (hunk 1 above)
Comment (alfetopito) [reply src/custom/pages/Claim/ClaimSummary.tsx:72]: Alright then

**Review by alfetopito — APPROVED** [review]
