### PR TITLE
Handle price impact error

### LINKED ISSUE #835: Paraswap price fails if price impact is too high
**Description**
The paraswap price fails if the price impact is too high

**How to Reproduce**
1. Go to Cowswap choose a random token pair
2. Do the same on Paraswap
3. Insert a value in Paraswap for which the price impact is too high or around 10%
4. Use this value on Cowswap
5.  The Price on Coswap is worse than Paraswap

**Expected behavior**
The same price should be displayed

**Screenshots**
Bildschirmfoto 2021-07-01 um 09 44 10
Bildschirmfoto 2021-07-01 um 10 05 58

### PR DESCRIPTION
**Pull request by anxolin**
image

Closes #835 #825

You can see in the picture how we receive now more tokens in these situations than current production version. 

Related to https://github.com/gnosis/cowswap/pull/839, which will make the error to go away, so it's not a 400 anymore. 
Anyways, I think for resiliance is good to also do this error handling on top of https://github.com/gnosis/cowswap/pull/839.
Bot PRs independently solve the issue, but is good to have both

### CODE REVIEW

**Comment by anxolin** [comment]
pls review after merge. cause i want to deploy to staging asap

File: src/custom/utils/paraswap.ts [hunk 1]
```diff
@@ -86,6 +97,11 @@ export async function getPriceQuote(params: PriceQuoteParams): Promise<ParaSwapP
     return rateResult
   } else {
     // Error getting the price
-    throw rateResult
+    const priceQuote = getPriceQuoteFromError(rateResult)
+    if (priceQuote) {
+      return priceQuote
+    } else {
+      throw rateResult
```
Comment (W3stside) [inline src/custom/utils/paraswap.ts:104]: you need a `try/catch` here as L100 will throw. or change L100 getPriceQuoteFromError to not throw and instead just return the error

**Review by W3stside — COMMENTED** [review]
need to review the throw logic
