### PR TITLE
[Hotfix - 1.5.2 fire ] - 1930/balances not loading

### LINKED ISSUE #1930: [1.5.0] Prod: Can't load balances for a WC wallet in XDAI and Rinkeby
1. Connect a WC wallet in XDAI and Rinkeby with the app
2. Open token list

**AR**: balances are not loaded
XDAI: 
image

Rinkeby: 
Video: https://watch.screencastify.com/v/Su2K1fl3eqbckjTSU9KV

**ER**: balances should appear

I was able to reproduce the issue with Gnosis Safe/Metamask
With WC imToken wallet I was able to see Mainnet  ETH balance in Rinkeby

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1930

This fix will manually set http.connection.url on the walletConnectProvider after the wallet is connected with based on the chainId that found on the signer and this will provide the correct infura link from which the balances should be loaded
  
# To Test

Try connecting with WalletConnect to one of the supported networks and see if the balances are loaded correctly

### CODE REVIEW

File: src/custom/components/WalletModal/WalletModalMod.tsx [hunk 1]
```diff
@@ -211,13 +212,22 @@ export default function WalletModal({
...
+          } else {
+            setPendingError(true)
+          }
+        })
+        .then(() => {
+          // manually set the WalletConnectConnector http.connection.url to currently connected network url
+          if (connector instanceof WalletConnectConnector) {
+            const { http, rpc, signer } = connector.walletConnectProvider
+            const chainId = (signer.connection as SignerConnection).chainId
+            http.connection.url = rpc.custom[chainId || 1]
```
Comment (anxolin) [inline src/custom/components/WalletModal/WalletModalMod.tsx:228]: hacky, but if it works, im fine. Only thing, can you add a comment, and also if there's a fix for WC point it to the PR or issue of the bug

Last but not least, could you avoid using "magic numbers", in this case we have a Chain enum

**Review by anxolin — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Hi @nenadV91 , great job!

The only thing is 1Inch wallet was enabled in Prod in v.1.6.0 app version. 
In the current PR the wallet is disabled, so it would be nice to enable it. 
enabled in 1 6

File: src/custom/components/WalletModal/WalletModalMod.tsx (hunk 1 above)
Comment (nenadV91) [reply src/custom/components/WalletModal/WalletModalMod.tsx]: Updated, I suggest we make sure this works correctly in our app as a fix and then I could create PR for WC package also.

**Comment by nenadV91** [comment]
@elena-zh This PR will first be merged in `hotfix/1.5.2` branch and then that branch will be merged into `master` which contains the update with the `1Inch` wallet supported I think. So the PR for the hotfix which is currently in draft state will have demo with the 1inch supported.

**Comment by elena-zh** [comment]
@nenadV91 , thanks for the explanation. 
I just thought that all hotfixes for a version should go before the next version. 
The current hotfix branch is 1.5.2, but we have already deployed 1.6, and are about to deploy 1.7.

**Comment by alfetopito** [comment]
@nenadV91 I think you should instead recreate the branch based off of master and cherry-pick the changes from this PR there, just to keep the history clean and without any potential regressions from 1.5
Also, the new hotfix version should be 1.6.1, since the latest is 1.6.0 ;)
