### PR TITLE
walletconnect QR code issue fix

### LINKED ISSUE #1787: [autoconnect] - wallet is not correctly connected and QR code remains
**Description**
Wallet is not correctly connected when adding a consecutive wallet via wallet connect. The QR code remains visible eventhough the wallet app shows that the wallet was connected. 
After closing the QR code and trying to connect the wallet again the wallet is connected with the wrong Logo. 
Related to #1680

**How to Reproduce**
1. Go to cowswap
2. Click on connect wallet and choose WC
3. scan QR code, etc..
4. Disconnect wallet
5. Repeat with a new wallet (not only another account but also another wallet provider) 
6. OR code is not closed, close it manually
7. Close modal 
8. try to connect again via WC
9. Wallet is autoconnected but displays the wrong logo #1788 

**Expected behavior**
Connecting a consecutive wallet via WC should be as smooth as adding it for the first time

**Screenshots**
Current issue
https://user-images.githubusercontent.com/34510341/140505618-eb5cf1e9-123d-4340-952b-cd677bc3acfd.mov

1. Connecting with safe
2. Then disconnecting the Safe
3. trying to connect a new wallet(Trust) with WC (0:22-0:40) - The trust app showed that I am connected
4. But QR code remains and cowswap shows that I am not connected
5. Trying to connect again --- auto connected with the Safe which I disconnected before

As comparison in production: 

https://user-images.githubusercontent.com/34510341/140505896-7029e466-8f88-40d7-a9ed-3f615a3a2f49.mov

**Additional context**
See slack conversation 
https://gnosisinc.slack.com/archives/C025G521XQD/p1636037993009000

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1787 and probably also #1788

This fixes the problem with random QR code that opens at some point after disconnect from the wallet and messes up the next wallet connection. The main problem seems to be in the previous version of @web3-react/walletconnect-connector so updating the version seems to fix the issue. I've also added removing of the value from local storage for latestProvider on wallet disconnect.

  # To Test

- We can use the steps mentioned in the issue connected to this PR

Previous PR -> https://github.com/gnosis/cowswap/pull/1904

### CODE REVIEW

File: src/custom/components/WalletModal/WalletModalMod.tsx [hunk 1]
```diff
@@ -206,7 +206,7 @@ export default function WalletModal({
     setWalletView(WALLET_VIEWS.PENDING)
 
     // if the connector is walletconnect and the user has already tried to connect, manually reset the connector
-    if (connector instanceof WalletConnectConnector && connector.walletConnectProvider?.wc?.uri) {
```
Comment (W3stside) [inline src/custom/components/WalletModal/WalletModalMod.tsx:209]: why remove this?

**Review by alfetopito — APPROVED** [review]

**Review by W3stside — APPROVED** [review]
make a note to create an issue detaiiling what happened and how we can potentially fix it

**Comment by elena-zh** [comment]
Since changes are merged, I reported a separate issue #1909 for the unresolved question in https://github.com/gnosis/cowswap/issues/1904#issuecomment-977638557
