### PR TITLE
[closes #1600] - Fix expert mode toggle switch

### LINKED ISSUE #1600: [Uni merge] Expert more 'Off' option is not highlighted in the settings
Related to #1413 and #1594

**Steps**: 
Open Settings modal when expert mode is off

**AR**:  'Off' option is not highlighted

**ER**: 'Off' option is highlighted

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

Closes #1600 - fixes expert mode toggle

Light
image

Dark
image

Edits theme a bit to change bg7 (unused) and avoids having to mod Toggle component just to change one SCSSS line. Reason we would have to mod and can't just target via CSS is that the prop is not accessible inside the override inside our own `custom/components/Toggle/index.tsx` file

unless someone has a better idea!

### CODE REVIEW

File: src/custom/theme/baseTheme.tsx [hunk 1]
```diff
@@ -25,6 +25,10 @@ export function colors(darkMode: boolean): Colors {
     bg1: darkMode ? '#1E1F2C' : '#FFFFFF',
     bg2: darkMode ? '#2C2D3F' : '#F7F8FA',
     bg3: darkMode ? '#1E1F2C' : '#EDEEF2',
+    bg4: darkMode ? '#021E34' : '#ffffff',
```
Comment (W3stside) [inline src/custom/theme/baseTheme.tsx:28]: bg4 - 7 come from develop (the branch i originally made this PR from before switching to release/1.3.0)

**Review by elena-zh — COMMENTED** [review]
Changes LGTM: currently, it is visible what mode is switched on. 
However, expert mode toggle has different colors for ON/OFF option. I have created a separate issue for this case #1646

**Review by elena-zh — APPROVED** [review]
