### PR TITLE
profile minors fix

### LINKED ISSUE #1545: Profile page: UI issues with copy icon and margins between elements
Originally reported in https://github.com/gnosis/cowswap/issues/1506#issuecomment-936296884

1. Copy icon placement is not fixed: still there is no margin between the link and the icon. it would be nice to add 8 px padding between them (Padding px value corresponds to the one near the copy icon in the side bar)
8 px copy

2. distance between 'Your referral url' and a referral link seems smaller than on the mock-up. Playing with a console, I notices that checking this box (see the image) might help to increase this distance: 
switch on
 
3. Margins are greater between icon-amount-section boarder in the mock-up

### PR DESCRIPTION
**Pull request by maria-vslvn**
# Summary

Fixes #1545

1. Copy icon was given a left indent of 8px
2. distance between 'Your referral url' and a referral link was increased
3. Margins between icons and texts are increased

  # To Test

1.  go to the [profile page](https://pr1604--gpswapui.review.gnosisdev.com/#/profile)

### CODE REVIEW

File: src/custom/pages/Profile/styled.tsx [hunk 1]
```diff
@@ -129,12 +130,14 @@ export const FlexCol = styled.div`
   justify-content: center;
   strong {
     font-size: 21px;
+    line-height: 32px;
```
Comment (alongoni) [inline src/custom/pages/Profile/styled.tsx:133]: Maybe:` line-height: 40px;` works better

**Comment by biocom** [comment]
A comment on this: It appears to me `line-height` is being used here, to achieve the effect of padding/margin (noteably top/bottom margin). Personally I think it's inappropriate to use line-height for that. When unexpected text wrapping occurs, you suddenly have wide gaps between text lines. I'd recommend using top/bottom padding for these scenarios instead.

File: src/custom/pages/Profile/styled.tsx [hunk 2]
```diff
@@ -129,12 +130,14 @@ export const FlexCol = styled.div`
   justify-content: center;
   strong {
     font-size: 21px;
+    line-height: 40px;
```
Comment (alongoni) [inline src/custom/pages/Profile/styled.tsx:133]: I agree with [Michel's comment](https://github.com/gnosis/cowswap/pull/1604#issuecomment-943104600), we should control spacing by using the margin (instead of increasing the line-height).
I.e: margin-top: 6px;

**Review by alongoni — CHANGES_REQUESTED** [review]

File: src/custom/pages/Profile/styled.tsx (hunk 2 above)
Comment (alongoni) [inline src/custom/pages/Profile/styled.tsx:133]: I agree with [Michel's comment](https://github.com/gnosis/cowswap/pull/1604#issuecomment-943104600), we should control the spacing by using the margin (instead of increasing the line-height).
For example: margin-top: 6px

**Comment by elena-zh** [comment]
It might be considered as a nitpick, but mobile paddings should be 14px ;)
image

**Comment by elena-zh** [comment]
Yes, @alongoni , thanks! The cow icon is missing when screen width is less than 485 px. 
@maria-vslvn , could you please fix it? 
Please, use behavior as it is currently implemented in the Prod version: https://cowswap.exchange/#/swap

**Review by alfetopito — APPROVED** [review]
