### PR TITLE
2082/no success on failure

### LINKED ISSUE #2082: Claim: 'Claimed!' message is displayed when a transaction fails
Related to #2000, #2009

1. Connect an account with tokens available to claim in Rinkeby
2. Connect a wallet
3. Open Claim  vCOW page
4. Press on the 'Claim vCOW' button
5. Specify conditions in transaction settings to get it failed (low-low gas fee, as an example)
6. Confirm the transaction in the connected wallet

**AR**: User gets a message about a successful Claim, however, the transaction fails

**ER:** it would be nice to show the 'claiming' state until transaction is successfully executed

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #2082 

No success on failure (😆)

Screen Shot 2022-01-28 at 15 18 37

When the claim tx fail, show instead a failure screen

https://user-images.githubusercontent.com/43217/151634032-26ff5d71-f468-4b70-8cd8-47d757553bbe.mov

User the can `go back` to a step before and try to do it again.

As a bonus, successful claims also have a `go back` button because there was no other way back than to change the account and try it again.

  # To Test

1. Either free or paid claims, proceed until you get the tx request in your wallet
2. Make the tx fail but inserting half the gas limit provided (e.g.: if you get 160000 replace it with 80000)

https://user-images.githubusercontent.com/43217/151634316-181b3687-0d74-4682-8767-7532cdc6c71a.mov

3. Submit the tx
* The tx will fail and you will lose the gas, but not the investments if any
* The UI will show you a failure screen and give you the option to go back
3. Click on `go back` and try to execute again
4. This time do not edit the tx parameters
* Once the tx is executed, you'll see the success screen

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , nicely done!

The only one issue I'd like to mention here is the design of the 'Go back' button: it is different than all the rest 'Go back' buttons on the form. So it would be nice to make them the same: 
New ones: 
dark
in black

Already implemented ones: 
like here
image

File: src/custom/pages/Claim/ClaimingStatus.tsx [hunk 1]
```diff
@@ -146,6 +150,20 @@ export default function ClaimingStatus() {
...
+
+      {isFailure && (
+        <>
+          {chainId && lastClaimTx?.hash && <EnhancedTransactionLink tx={lastClaimTx} />}
+          <AttemptFooter>
+            <p>The claim transaction failed. Please check the network parameters and try again.</p>
+          </AttemptFooter>
+        </>
+      )}
+      {(isConfirmed || isFailure) && (
```
Comment (anxolin) [inline src/custom/pages/Claim/ClaimingStatus.tsx:162]: I think the go back should only be there for the failure. 

For the success, we should have a "Change account" that does the reset. Otherwise, i can just go back and try to claim again, and I get:
image

**Review by anxolin — COMMENTED** [review]
The failure handling works very nice. 

Only concerned is the back button on success

**Comment by anxolin** [comment]
Merging to consolidate the RC. The concerned i had was addressed in #2358.
@biocom, maybe evaluate if we want to review the style comments from Elena or if its fine
