### PR TITLE
Slippage in expert mode

### LINKED ISSUE #1141: [0.17] Expert mode doesn't show the amount after slippage
**Description**

Expert mode doesn't show the amount after slippage

Proposed solution: Conditionally show min. received (excl. fees) in Expert mode, at the bottom (given no confirmation modal).

**How to Reproduce**
1. Activate the expert mode
2. Fill in the order details (sell order)
3. Click on Swap
4. The sell amount in the signature request doesn't match the `min received` displayed

**Expected behavior**
On expert mode where there's no confirmation modal, there should be a place where we display the actual received value with the slippage applied

**Additional context**
Reported by Felix on Slack https://gnosisinc.slack.com/archives/CSGLUC1BN/p1627651170006300

### PR DESCRIPTION
**Pull request by anxolin**
# Summary: Shows slippage and amount after slippage in expert mode

Closes #1141 

# Notes for reviewer
The main goal of this PR is to show the slippage and amounts after slippage, however, in order to show the slippage in the widget and not copy-past the code I had to refactor the two elements into 2 components:
* `RowSlippage`
* `RowReceivedAfterSlippage`

These 2 components were used both in the confirmation modal and in the widget.

On top of this, this uses `RowSlippage` in the widget when the slippage is non-AUTO, this fixes one issue we had and was not reported yet where:
- we didn't have tooltip for the slippage
- style was a bit different

# To Test

1. Verify that non expert mode doesn't show the slippage in the swap component directly. It's only shown in the confirmation modal.
image

image

2. Test that advanced mode, show the slippage and the min receive amount already in the swap component.
image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hi @anxolin , great job! The only thing is that slippage tolerance appears twice on the form when it is not set to 'Auto' 
image
image
It would be nice to remove one of them.. May be that one that does not have a tooltip.

Thanks!

**Comment by anxolin** [comment]
Great catch @elena-zh ! 

I fixed it, plus I also made it use the same formatting and add the missing tooltip that it had:

image

I hope is better now.

**Comment by elena-zh** [comment]
Hey @anxolin , the last commit build seems to be failed: I do not see changes to re-test. 
Could you please take a look?

**Review by elena-zh — APPROVED** [review]
Great job!

I have faced the known tooltip issue on the swap form reported in #1079 . I Have added a comment about it there. 

Thanks

File: src/custom/components/swap/TradeSummary/TradeSummaryMod.tsx [hunk 1]
```diff
@@ -44,23 +41,14 @@ export default function TradeSummary({
...
   const theme = useContext(ThemeContext)
-  // const { priceImpactWithoutFee, realizedLPFee } = computeTradePriceBreakdown(trade)
-  const { /* priceImpactWithoutFee, */ realizedFee } = React.useMemo(() => computeTradePriceBreakdown(trade), [trade])
-  const isExactIn = trade.tradeType === TradeType.EXACT_INPUT
-  const slippageAdjustedAmounts = computeSlippageAdjustedAmounts(trade, allowedSlippage)
-
-  const [slippageOut, slippageIn] = useMemo(
-    () => [slippageAdjustedAmounts[Field.OUTPUT], slippageAdjustedAmounts[Field.INPUT]],
-    [slippageAdjustedAmounts]
-  )
```
Comment (alfetopito) [inline src/custom/components/swap/TradeSummary/TradeSummaryMod.tsx:55]: Is this part of the original file? Shouldn't comment instead of deleting?

**Review by alfetopito — COMMENTED** [review]
Minor comment
