### PR TITLE
1120/consistent usd estimation and amounts display

### LINKED ISSUE #1120: Issue broken fee price
**Description**
the UI was broken in xDAI where the fee was very small:
image

It auto-fixed itself after some minutes:
image

**How to Reproduce**
1. Go to xDAI
2. Get an estimation

**Expected behavior**
One proposal is something like this:
image

### PR DESCRIPTION
**Pull request by anxolin**
> Reopening #1127, i rushed the merge. There's issues to address in #1129. cc/ @alfetopito 

# Summary

Fixes #1120
Fixes https://github.com/gnosis/cowswap/issues/1129

Adjusting display of fiat amounts and fee amount
Adjusting every other amount as well

## Before
screenshot_2021-07-29_15-11-41

## After
screenshot_2021-07-29_15-38-54
screenshot_2021-07-29_15-16-25

# To Test

1. On xDai, pick a wxDai and WETH
2. Insert a tiny wxDai amount (0.001)
- [ ] USD estimations should show `< 0.01`
- [ ] Fee amount should display `< 0.00001`

# Background

PR expanded to include adjustment in all amounts displayed

## Swap
screenshot_2021-08-05_14-35-40

## Confirmation
screenshot_2021-08-05_14-35-52

## Waiting for confirmation
screenshot_2021-08-05_14-36-10

## Order placed notification
screenshot_2021-08-05_14-36-21

## Order details
screenshot_2021-08-05_14-37-04

## Order traded notification
screenshot_2021-08-05_14-37-10

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , changes look good to me!
However, I'm a bit confused with different number of decimals in several places. Look: here the expert mode, and the form  shows `Minimum received (incl. fee)` amount with 6 decimals. However, all the rest amounts (Fee/notification pop-ups/transaction detail)  show amount <0.001 (4 decimals)
same number
Actually, amount with 6 decimals is displayed confirmation pop-up when we work in the regular mode, but in this case it is not so visible as in the expert mode.. 
May be we should use the same amount of decimals in all numbers?

Also, it might be related to #1166 or, but.. we could show the whole amount on hover on the Waiting For Confirmation pop-up.. WDYT?
whole

**Comment by alfetopito** [comment]
> Hey @alfetopito , changes look good to me!
> However, I'm a bit confused with different number of decimals in several places. Look: here the expert mode, and the form shows `Minimum received (incl. fee)` amount with 6 decimals. However, all the rest amounts (Fee/notification pop-ups/transaction detail) show amount <0.001 (4 decimals)
> same number
> Actually, amount with 6 decimals is displayed confirmation pop-up when we work in the regular mode, but in this case it is not so visible as in the expert mode..
> May be we should use the same amount of decimals in all numbers?

I think this came up before but for some reason we decided to keep as is (which means, same as Uniswap)
Now that we have better control over what's displayed, it could make sense to use the same amount of decimals everywhere.

Then we have to decide: should we use `6` or `4` decimals as default for amounts?

What are your thoughts? @elena-zh @anxolin @W3stside @biocom

> 
> Also, it might be related to #1166 or, but.. we could show the whole amount on hover on the Waiting For Confirmation pop-up.. WDYT?

Good point, I missed that one. I'll add the title there too.

**Comment by alfetopito** [comment]
@elena-zh 
> Good point, I missed that one. I'll add the title there too.

Added tooltip to `waiting for confirmation modal`

**Comment by elena-zh** [comment]
> Then we have to decide: should we use 6 or 4 decimals as default for amounts?
> What are your thoughts? @elena-zh @anxolin @W3stside @biocom

I vote for 4

**Comment by elena-zh** [comment]
@alfetopito , now I can see titles for numbers on the `waiting for confirmation` modal.

Thanks!

**Comment by W3stside** [comment]
@alfetopito sorry if this was discussed but do we want the low threshold representation of numbers in the toast notifications?

IMHO looks a little weird but I'm fine with it if it's previously been discussed and approved

File: src/custom/components/swap/ConfirmSwapModal/index.tsx [hunk 1]
```diff
@@ -1,4 +1,32 @@
...
+import { Trans } from '@lingui/macro'
+
+import ConfirmSwapModalMod from './ConfirmSwapModalMod'
+import TradeGp from 'state/swap/TradeGp'
+import { formatSmart } from 'utils/format'
 
 export * from './ConfirmSwapModalMod'
-export default ConfirmSwapModal
+
+function buildPendingText(trade: TradeGp | undefined): JSX.Element {
```
Comment (W3stside) [inline src/custom/components/swap/ConfirmSwapModal/index.tsx:10]: nit: should be capitalised if it's a component, probably can just be `PendingText`

File: src/custom/components/swap/FeeInformationTooltip.tsx [hunk 2]
```diff
@@ -119,7 +122,7 @@ export default function FeeInformationTooltip(props: FeeInformationTooltipProps)
           }
         />
       </span>
-      <FeeAmountAndFiat>
+      <FeeAmountAndFiat title={`${fullFeeAmount || '-'} ${symbol || ''}`}>
```
Comment (W3stside) [inline src/custom/components/swap/FeeInformationTooltip.tsx:125]: i believe you can set defaults to the initial const declaration for both of these inside the destructured array return on L 81 but I may be wrong

File: src/custom/components/swap/TradePrice/TradePriceMod.tsx [hunk 3]
```diff
@@ -33,21 +33,19 @@ export const StyledPriceContainer = styled.button`
   }
 `
 
-const PRICE_FORMAT_OPTIONS: [number, FormatSmartOptions] = [DEFAULT_PRECISION, { smallLimit: '0.00001' }]
```
Comment (W3stside) [inline src/custom/components/swap/TradePrice/TradePriceMod.tsx:36]: noooooooooo _cries_

File: src/custom/components/swap/TradeSummary/index.tsx [hunk 4]
```diff
@@ -101,6 +101,12 @@ export function RowReceivedAfterSlippage({
   )
   const isExactIn = trade.tradeType === TradeType.EXACT_INPUT
 
+  const [outAmount, outSymbol] = isExactIn
```
Comment (W3stside) [inline src/custom/components/swap/TradeSummary/index.tsx:104]: nit: the name out here doesn't make sense for in amounts etc. i see what you're doing but maybe rethink the name to sth like `swapAmount` or similar

File: src/custom/utils/format.ts [hunk 5]
```diff
@@ -17,10 +16,29 @@ export interface FormatSmartOptions {
   isLocaleAware?: boolean
 }
 
+function _buildSmallLimit(smallLimit: string | undefined, decimalsToShow: number): string {
```
Comment (W3stside) [inline src/custom/utils/format.ts:19]: cool!

File: src/custom/utils/format.ts [hunk 6]
```diff
@@ -32,13 +50,15 @@ export function formatSmart(
 
   const precision = value instanceof CurrencyAmount ? value.currency.decimals : 0
   const amount = value instanceof CurrencyAmount ? value.quotient.toString() : value.toFixed(decimalsToShow)
+  // Take the min(decimalsToShow, token decimals) because a token can have less decimals than the what we want to show
+  const smallLimitPrecision = Math.min(decimalsToShow, precision || DEFAULT_DECIMALS)
```
Comment (W3stside) [inline src/custom/utils/format.ts:54]: precision here is always a value - tho this ternary will see the `0` fallthrough condition in the ternary as false and take DEFAULT_DECIMALS. This is intended? else do 
`const smallLimitPrecision = Math.min(decimalsToShow, precision ?? DEFAULT_DECIMALS)`

**Review by W3stside — APPROVED** [review]
super nice. just minor comments

**Review by MareenG — APPROVED** [review]
Looks good. 
One thing I noticed again here is the inconsitency of rounding/ or cutting. 


https://user-images.githubusercontent.com/34510341/128871139-a344e518-e369-4b62-b989-63aaee8d33bf.mov


 In this Example you can see that 
0.238951 SNX are swapped for 2.4716 DAI and the user receives 2.4638 DAI after fees. 
If you hover over you get the precision of 
0.2389505... SNX for 2.471636.. DAI and after fees 2.463877.. DAI
This shows that we round 0.2389**505**... to 0.2389**51** SNX
But cut 2.463**877** DAI to 2.463**8** DAI

Not directly connected to this PR but with displaying the precise amounts this gets a bit more obvious.  I personally think it would be nice to either cut or round the values consistently and not mix both approaches.

File: src/custom/components/swap/ConfirmSwapModal/index.tsx (hunk 1 above)
Comment (alfetopito) [reply src/custom/components/swap/ConfirmSwapModal/index.tsx:10]: Good point, will update

File: src/custom/components/swap/TradePrice/TradePriceMod.tsx (hunk 3 above)
Comment (alfetopito) [reply src/custom/components/swap/TradePrice/TradePriceMod.tsx:36]: :wave:

**Comment by alfetopito** [comment]
> Looks good.
> One thing I noticed again here is the inconsitency of rounding/ or cutting.
> Bildschirmaufnahme.2021-08-10.um.14.48.52.mov
> 
> In this Example you can see that
> 0.238951 SNX are swapped for 2.4716 DAI and the user receives 2.4638 DAI after fees.
> If you hover over you get the precision of
> 0.2389505... SNX for 2.471636.. DAI and after fees 2.463877.. DAI
> This shows that we round 0.2389**505**... to 0.2389**51** SNX
> But cut 2.463**877** DAI to 2.463**8** DAI
> 
> Not directly connected to this PR but with displaying the precise amounts this gets a bit more obvious. I personally think it would be nice to either cut or round the values consistently and not mix both approaches.

@MareenG and @W3stside 

This has not been decided (whether to make it uniform and make everything either 4 or 6 decimals precision).
See my comment here asking for input https://github.com/gnosis/cowswap/pull/1135#issuecomment-894380336 :)

Independent of the direction we agree on (everything 4 or 6, or leave as is), I'd like to address that in a separated PR as this one is quite large already.

File: src/custom/utils/format.ts (hunk 6 above)
Comment (alfetopito) [reply src/custom/utils/format.ts:54]: This is a tricky one.

I'll do as you suggest because I don't remember the reason why I did it like that... which I knew when I started typing but lost track :shrug:

**Review by elena-zh — APPROVED** [review]

**Comment by anxolin** [comment]
> Not directly connected to this PR but with displaying the precise amounts this gets a bit more obvious. I personally think it would be nice to either cut or round the values consistently and not mix both approaches.

@MareenG I think we didn't do this rounding on porpouse, afaik is something that came from Uniswap. However, it's a good thing in my view. I think we want to be pessimistic when we round, so telling the user it's worse than actually is. This means that we round UP for the sell amount, and DOWN for the receive one. 
@alfetopito do you know if this is always the case and the reason on the numbers Mareen brought up?

>  make everything either 4 or 6 decimals precision
4 seems fine to me

File: src/custom/utils/format.ts [hunk 7]
```diff
@@ -17,10 +16,29 @@ export interface FormatSmartOptions {
   isLocaleAware?: boolean
 }
 
+function _buildSmallLimit(smallLimit: string | undefined, decimalsToShow: number): string {
+  if (smallLimit) {
```
Comment (anxolin) [inline src/custom/utils/format.ts:20]: nit: maybe add some comment in the fn, so u explain what is it doing. 
I understand you want to dynamically generate the smallest amount for different currencies depending on their precision.  Good be good to add it, plus some examples (including that `1` case)

**Review by anxolin — COMMENTED** [review]
APPROVE

**Comment by anxolin** [comment]
nitpicking: this should be `< $0.01` instead of `~ $< 0.01`
image

**Comment by MareenG** [comment]
> I think we want to be pessimistic when we round, so telling the user it's worse than actually is. This means that we round UP for the sell amount, and DOWN for the receive one.

Ok this makes sense then. It always bothered me from a mathematical point of view.

File: src/custom/components/swap/ConfirmSwapModal/index.tsx [hunk 8]
```diff
@@ -1,4 +1,35 @@
...
+  const inputAmount = trade?.inputAmount
+  const inputSymbol = inputAmount?.currency?.symbol
+  const outputAmount = trade?.outputAmount
+  const outputSymbol = outputAmount?.currency?.symbol
+
+  return (
+    <Trans>
+      Swapping{' '}
+      <span title={`${inputAmount?.toFixed(inputAmount?.currency.decimals)} ${inputSymbol}`}>
+        {formatSmart(inputAmount) /* trade?.inputAmount?.toSignificant(6) */} {inputSymbol}
```
[the remark this answers is not in the document]
Comment (alfetopito) [reply src/custom/components/swap/ConfirmSwapModal/index.tsx:21]: Good point, will update

**Comment by elena-zh** [comment]
I have created a separate issue to make all amounts 4 decimals precision #1268
