### PR TITLE
Fix appDataHash initial state being undefined when state was rehydrated from local storage

### LINKED ISSUE #1736: Cannot place an order in BARN
Cannot place an order in BARN

**Expected**: user is able to place an order in Barn

### PR DESCRIPTION
**Pull request by ramirotw**
# Summary

Fixes #1736

The problem was that `appDataHash` wasn't defined as nullable in `AffiliateState` and since the value was introduced after the `referrerAddress`, there was already a `redux_localstorage_simple_affiliate` key in local storage, that caused the `redux-localstorage-simple` middleware to load either an empty Affiliate state or just with the old `referrerAddress` key, causing the `initialState`:

```js
export const initialState: AffiliateState = {
  referralAddress: '',
  appDataHash: APP_DATA_HASH,
}
```

to never being called and so `appDataHash` was undefined and the Swap call failed.

  # To Test

1. Open the devtools and in Application > Local Storage, find the key `redux_localstorage_simple_affiliate` and set it to `{}`
image
2. Refresh the browser immediately as any redux action will trigger a local storage update and the `redux_localstorage_simple_affiliate` will be updated with a default `appDataHash` value.
3. Make a Swap and it shouldn't fail

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
I was not able to reproduce this issue according to the described steps.

**Review by alfetopito — APPROVED** [review]
Simple fix, managed to place an order without issues.
Although I never saw the issue in the first place, so we might need more testing for those who could reproduce it before.

File: src/custom/state/affiliate/hooks.ts [hunk 1]
```diff
@@ -1,13 +1,14 @@
...
 import { useAppDispatch } from 'state/hooks'
 import { updateAppDataHash, updateReferralAddress } from 'state/affiliate/actions'
-import { useCallback } from 'react'
 import { generateReferralMetadataDoc, uploadMetadataDocToIpfs } from 'utils/metadata'
+import { APP_DATA_HASH } from 'constants/index'
 
 export function useAppDataHash() {
   return useSelector<AppState, string>((state) => {
-    return state.affiliate.appDataHash
+    return state.affiliate.appDataHash || APP_DATA_HASH
```
Comment (anxolin) [inline src/custom/state/affiliate/hooks.ts:11]: it works. 

In some other cases similar to this one, we just updated the state to have the "default" missing props when we notice they are un-initialized. Your approach was more like assuming it can be nullable and return a default.

**Review by anxolin — COMMENTED** [review]
APPROVE
