### PR TITLE
Claim change account

### LINKED ISSUE #2097: [CLAIM] Switch account functionality
- Switch account is allowed in step 1 and 2, but not in the last one
- Make sure all cases are taken into accoun (i.e. nothing is broken if you refresh or change account in any moment in the process)

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

Closes #2097 

DO NOT show "Change account" button on last investment step as seen in issue linked. 
On user account change (in wallet) reset them to the ClaimsTable and initial investment step

  # To Test
1. use an account with investment
2. get to last step
3. change account and see where ya at
4. click next after selecting an investment and see you are at step 1

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @W3stside , I'd remove 'Change account' from the 'Claiming' screen as well. WDYT?
image

**Comment by elena-zh** [comment]
I also have found an issue, that seems to be related to the current PR: set allowance form is empty when change an account. See the video: https://watch.screencastify.com/v/11AejUiOcRtM5XV8AILH
Steps: 
1. Connect to a wallet in Rinkeby with account that has investment claims
2. Select investment claim
3. Navigate to the Sett allowance screen
4. Press on the 'Change account'
5. Fill in Recipient field **with the same account**
6. Press on the 'Checn claimable vCOW' button

**AR**: set allowance form does not contains claim options

As expected result. I would propose redirect to the ClaimsTable and initial investment step

**Comment by biocom** [comment]
Spotted the same issues @elena-zh mentioned. Also a small merge conflict pending.

**Comment by W3stside** [comment]
> 4d79426

nice catch!

fixed here: 4d79426

**Comment by elena-zh** [comment]
Hey @W3stside , Is this issue related to the current PR? 
image
Steps are in the video: https://watch.screencastify.com/v/oL02VLk1qKgRbqmAZ8YS

**Comment by elena-zh** [comment]
@W3stside , 'Change account' has started to be displayed in the 'Confirm transaction to claim all vCOW' screens: 
image
image

**Review by anxolin — APPROVED** [review]

File: src/custom/pages/Claim/ClaimNav.tsx [hunk 1]
```diff
@@ -28,13 +28,19 @@ export default function ClaimNav({ account, handleChangeAccount }: ClaimNavProps
         <ClaimAccountButtons>
           {!!account && account !== activeClaimAccount && (
             <ButtonSecondary disabled={isAttempting} onClick={() => setActiveClaimAccount(account)}>
-              Your claims
+              Change account to connected wallet
```
Comment (anxolin) [inline src/custom/pages/Claim/ClaimNav.tsx:31]: probably a bit too big. But I guess when Michel review responsive, we might move these and re-label them

Comment (W3stside) [reply src/custom/pages/Claim/ClaimNav.tsx]: changed it again but let's review outside this pr

**Review by alfetopito — APPROVED** [review]
