### PR TITLE
Fix inverted invested amounts

### LINKED ISSUE #2423: [Claim] Inverted UserOption & GnoOption investment amounts
**Description**

Some users are facing the issue where, UserOption & GnoOption investment amounts are swapped.

Example of a executed tx using the wrong amounts https://blockscout.com/poa/xdai/tx/0xe3f4732449e14515526adef4c0738da7ed5a565297273d428a4de3d542c503bc

**How to Reproduce**

Not clear yet how to reproduce, other than it happens when there are at least 2 investment options.

1. Go to claim page
2. With a wallet that has 2 investment options (UserOption and GnoOption) available, check for the airdrop
3. Select both options, proceed to investment amounts page
4. Fill in max for both option
5. Move to review step
6. Here is where there have been reports of investment amounts being flipped

**Expected behavior**
Investment amounts are not inverted

**Screenshots**

On Gchain
inverted_investment
On Mainnet
image

**Additional context**

It has been reported both on Gchain and Mainnet.
Also both for self investment as well as investment on behalf of someone else.

The upside of investing for someone else is that the code (and the contract) will only accept 100% claim, so there's no way to "burn" the investment with wrong amounts.
When investing for the connected account it can be a problem, which can at least be detected on the last step.

**Mitigation**

For now there are 3 ways to prevent the issue that I can think of
1. Do not invest yet, wait until we can fix the issue
2. Invest in 1 option at a time. Might cost you more gas due to multiple txs required
3. Use another account to claim the investment options on the account's behalf

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #2423

Fixing issue that under some circumstances will result in the investment amounts being inverted.

Keep in mind this only happens when there are at least 2 investment options selected.

  # To Test

1. With any account that has 2 or more investment options, load it in the claim ui
2. When selecting the claims, start ticking the boxes from bottom up of at least 2 claims
3. On investment screen, opt to invest max amount on all
4. Proceed to review screen
* Amounts selected should match the previous screen

If you test the same thing on Prod or anywhere else that doesn't have this fix, it'll have the amounts inverted, like in this video

https://user-images.githubusercontent.com/43217/154154098-519c0f2a-c04c-4d14-a3d1-50dae2a7ee3b.mov

### CODE REVIEW

File: src/custom/state/claim/hooks/index.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ import useIsMounted from 'hooks/useIsMounted'
 import { ChainId } from '@uniswap/sdk'
 import { ClaimInfo } from 'state/claim/reducer'
 
-const CLAIMS_REPO_BRANCH = 'gip-13'
+const CLAIMS_REPO_BRANCH = '2022-02-15_Rinkeby-full'
```
Comment (alfetopito) [inline src/custom/state/claim/hooks/index.ts:65]: Note to self: revert this commit before merging, we don't want to change the claims repo branch

**Review by W3stside — APPROVED** [review]
Nice find

**Review by anxolin — APPROVED** [review]
So at the end it was that confusion of using the index of the array instead of the one from the claiming. Not sure if it was conscious decision, but it is a bad idea to rely on the order of the arrays

Nice 🕵️‍♀️ job Leandro!


pls, don't forget to revert the branch name before merging

**Review by elena-zh — APPROVED** [review]
LGTM!
